### PR TITLE
Update with purity-inference features

### PR DESCRIPTION
**Pull request by kili-ilo**
Broken! Work In Progress!

My build is frozen at this step:

```
[jan@framey roc-platform-template-rust]$ cargo build
   Compiling libc v0.2.150
   Compiling static_assertions v1.1.0
   Compiling arrayvec v0.7.6
   Compiling roc_host v0.0.1 (/home/jan/_code/_roc/roc-platform-template-rust/crates/roc_host)
   Compiling roc_std v0.0.1 (https://github.com/roc-lang/roc.git?branch=purity-inference#2b8d9aa4)
    Building [================>           ] 7/11: roc_host(build)                                
```

### CODE REVIEW

**Comment by lukewilliamboswell** [comment]
Using `cargo build -vvv` I can see
```
ocuments/GitHub/roc-platform-template-rust/target/debug/build/roc_host-e30e65c858e3d757/build-script-build`
[roc_host 0.0.1] cargo:rustc-link-search=/Users/luke/Documents/GitHub/roc-platform-template-rust/platform
[roc_host 0.0.1] cargo:rustc-link-lib=dylib=app
[roc_host 0.0.1] cargo:rerun-if-changed=/Users/luke/Documents/GitHub/roc-platform-template-rust/platform/main.roc
[roc_host 0.0.1] thread 'main' panicked at crates/compiler/load_internal/src/file.rs:1722:37:
[roc_host 0.0.1] There were still outstanding Arc references to module_ids
[roc_host 0.0.1] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by lukewilliamboswell** [comment]
Added some fixes for the roc side... next up is updating the rust host. I generated the LLVM IR using 
```sh
$ roc build --no-link --emit-llvm-ir app.roc
```

And from that I can see 

```llvm
define { [1 x i32], i8 } @roc__mainForHost_1_exposed({} %0) !dbg !176 {
entry:
  %result_value = alloca { [1 x i32], i8 }, align 8
  call fastcc void @"_mainForHost!_11922f5e717257e3c76632973ee406cbf106889cd4e80e37d14c1d9c194671"({} %0, ptr %result_value), !dbg !177
  %load_result = load { [1 x i32], i8 }, ptr %result_value, align 4, !dbg !177
  ret { [1 x i32], i8 } %load_result, !dbg !177
}
```

So we'll want to update the FFI in `crates/roc_host/src/lib.rs` to match that. Checkout roc-ray for an example.

**Comment by lukewilliamboswell** [comment]
Completed the upgrade for purity-inference. This should be ready to merge as soon as the feature lands in roc main. 😄

**Comment by kili-ilo** [comment]
This is what I'm seeing - am I building it wrong?

```
[jan@framey roc-platform-template-rust]$ git status
On branch purity-inference
Your branch is up to date with 'origin/purity-inference'.

nothing to commit, working tree clean
[jan@framey roc-platform-template-rust]$ roc version
roc: /lib64/libtinfo.so.6: no version information available (required by roc)
roc nightly pre-release, built from commit 8dbc909 on Fr 15 Nov 2024 09:02:07 UTC
[jan@framey roc-platform-template-rust]$ roc build.roc
roc: /lib64/libtinfo.so.6: no version information available (required by roc)
BUILD INFO: Geting native target...
BUILD INFO: Building cargo; mode: DEBUG for target LinuxX64...
    Updating crates.io index
    Updating git repository `https://github.com/roc-lang/roc.git`
     Locking 6 packages to latest compatible versions
      Adding libc v0.2.150 (latest: v0.2.164)
   Compiling libc v0.2.150
   Compiling roc_host v0.0.1 (/home/jan/_code/_roc/roc-platform-template-rust/crates/roc_host)
   Compiling arrayvec v0.7.6
   Compiling static_assertions v1.1.0
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-unknown-linux-musl`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `static_assertions` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-unknown-linux-musl`

error: could not compile `arrayvec` (lib) due to 1 previous error
Program exited with error:
    (ErrBuildingRustTarget (CmdError (ExitCode -99)))

Tip: If you do not want to exit on this error, use `Task.mapErr` to handle the error.
Docs for `Task.mapErr`: <https://www.roc-lang.org/packages/basic-cli/0.15.0/Task#mapErr>
[jan@framey roc-platform-template-rust]$ 
```

**Comment by lukewilliamboswell** [comment]
The error message suggests `rustup target add x86_64-unknown-linux-musl`, can you try that?

**Pull request merged**
